#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1
#SBATCH --job-name=rf_t12
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=60:00:00
#SBATCH --mem=120000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

source activate rib

DATA_ROOT=/scratch-shared/$USER/data/

CKPT="checkpoints/expf12_final/epoch=28-step=80156.ckpt"

cd ~/rib-fracture

python eval.py --ckpt $CKPT --data-root $DATA_ROOT --download-data --test-stride 32 --batch-size-test 32 --num-workers 18 --set val
